name: Frontend Tests + Push

on:
    push:
        branches:
        - master
        paths:
        - consuming-frontend/**
        
jobs:
    ci:
        runs-on: ubuntu-latest
        container:
            image: node 
        
        steps:
            - uses: actions/checkout@v1
            - name: Set up NodeJS
              uses: actions/setup-node@v1
              with:
                node-version: '10.x'
            - name: Install Dependencies    
              working-directory: ./consuming-frontend  
              run: npm install
            - name: Run Tests  
              working-directory: ./consuming-frontend  
              run: npm test
              env:
                CI: true 
                
    cd: 
        runs-on: ubuntu-latest
        needs: ci
        env: 
          IMAGE_TAG: events-communication-consuming-frontend
        
        steps:
            - uses: actions/checkout@v1
            - name: Docker login
              run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build
              working-directory: ./consuming-frontend
              run: docker build -t ${{ env.IMAGE_TAG }} .  
            - name: Tags  
              run: |
                docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:${{ github.sha }}
                docker tag ${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest
            - name: Push
              run: |
                docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:${{ github.sha }}
                docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_TAG }}:latest

              